version: "3"
services:
  mqtt:
    image: iqtlabs/edgetech-mqtt:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: unless-stopped
  http-uploader:
    image: iqtlabs/edgetech-http-uploader:latest
    build:
      context: ./edgetech-http-uploader/http-uploader
      dockerfile: ./Dockerfile
    restart: unless-stopped
    depends_on: 
      - mqtt
    environment:
      - WEBHOOK_URL=${WEBHOOK_URL:?error}
      - WEBHOOK_TOKEN=${WEBHOOK_TOKEN:?error}
    env_file:
      - .env
