version: "3"
services:
  mqtt:
    image: iqtlabs/edgetech-mqtt:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: unless-stopped
  http-uploader:
    image: iqtlabs/edgetech-http-uploader:latest
    build:
      context: ./http-uploader
      dockerfile: ./Dockerfile
    restart: unless-stopped
    depends_on: 
      - mqtt
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"